// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicTechnologies.Data;

namespace Quaverflow.Data.Migrations
{
    [DbContext(typeof(QuaverflowDbContext))]
    [Migration("20210305131922_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntervalMode", b =>
                {
                    b.Property<int>("IntervalsId")
                        .HasColumnType("int");

                    b.Property<int>("ModesId")
                        .HasColumnType("int");

                    b.HasKey("IntervalsId", "ModesId");

                    b.HasIndex("ModesId");

                    b.ToTable("IntervalMode");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientGroupId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientSubGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientGroupId");

                    b.HasIndex("IngredientSubGroupId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngredientGroups");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IngredientGroupId")
                        .HasColumnType("int");

                    b.Property<string>("SubGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientGroupId");

                    b.ToTable("IngredientSubGroups");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ScaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScaleId");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Scale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("QuaverflowUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scales");
                });

            modelBuilder.Entity("IntervalMode", b =>
                {
                    b.HasOne("Quaverflow.Data.MusicModels.Interval", null)
                        .WithMany()
                        .HasForeignKey("IntervalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quaverflow.Data.MusicModels.Mode", null)
                        .WithMany()
                        .HasForeignKey("ModesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Ingredient", b =>
                {
                    b.HasOne("Quaverflow.Data.FoodModels.IngredientGroup", "IngredientGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quaverflow.Data.FoodModels.IngredientSubGroup", "IngredientSubGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientGroup");

                    b.Navigation("IngredientSubGroup");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientSubGroup", b =>
                {
                    b.HasOne("Quaverflow.Data.FoodModels.IngredientGroup", "IngredientGroup")
                        .WithMany("IngredientSubGroups")
                        .HasForeignKey("IngredientGroupId");

                    b.Navigation("IngredientGroup");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Mode", b =>
                {
                    b.HasOne("Quaverflow.Data.MusicModels.Scale", "Scale")
                        .WithMany("Modes")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientGroup", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("IngredientSubGroups");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientSubGroup", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Scale", b =>
                {
                    b.Navigation("Modes");
                });
#pragma warning restore 612, 618
        }
    }
}
