// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MusicTechnologies.Data;

namespace Quaverflow.Data.Migrations
{
    [DbContext(typeof(QuaverflowDbContext))]
    partial class QuaverflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntervalMode", b =>
                {
                    b.Property<int>("IntervalsId")
                        .HasColumnType("int");

                    b.Property<int>("ModesId")
                        .HasColumnType("int");

                    b.HasKey("IntervalsId", "ModesId");

                    b.HasIndex("ModesId");

                    b.ToTable("IntervalMode");
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContinentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContinentId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HospitalBedsPerThousand")
                        .HasColumnType("float");

                    b.Property<double?>("HumanDevelopmentIndex")
                        .HasColumnType("float");

                    b.Property<double>("InfectionDeathRatio")
                        .HasColumnType("float");

                    b.Property<double?>("LifeExpectancy")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<double?>("PopulationDensity")
                        .HasColumnType("float");

                    b.Property<double>("RatioDeathToPopulation")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.CovidDailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("GDPPerCapita")
                        .HasColumnType("float");

                    b.Property<int>("NewCases")
                        .HasColumnType("int");

                    b.Property<int>("NewDeaths")
                        .HasColumnType("int");

                    b.Property<double>("RRate")
                        .HasColumnType("float");

                    b.Property<double>("StringencyIndex")
                        .HasColumnType("float");

                    b.Property<int>("TotalCases")
                        .HasColumnType("int");

                    b.Property<int>("TotalDeaths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("CovidDailySummaries");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientGroupId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientSubGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientGroupId");

                    b.HasIndex("IngredientSubGroupId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngredientGroups");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IngredientGroupId")
                        .HasColumnType("int");

                    b.Property<string>("SubGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientGroupId");

                    b.ToTable("IngredientSubGroups");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serves")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UnitMeasure")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeStep");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ScaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScaleId");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Scale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Scales");
                });

            modelBuilder.Entity("IntervalMode", b =>
                {
                    b.HasOne("Quaverflow.Data.MusicModels.Interval", null)
                        .WithMany()
                        .HasForeignKey("IntervalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quaverflow.Data.MusicModels.Mode", null)
                        .WithMany()
                        .HasForeignKey("ModesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.Country", b =>
                {
                    b.HasOne("Quaverflow.Data.CovidModels.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId");

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.CovidDailySummary", b =>
                {
                    b.HasOne("Quaverflow.Data.CovidModels.Country", "Country")
                        .WithMany("DailySummary")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Ingredient", b =>
                {
                    b.HasOne("Quaverflow.Data.FoodModels.IngredientGroup", "IngredientGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quaverflow.Data.FoodModels.IngredientSubGroup", "IngredientSubGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientGroup");

                    b.Navigation("IngredientSubGroup");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientSubGroup", b =>
                {
                    b.HasOne("Quaverflow.Data.FoodModels.IngredientGroup", "IngredientGroup")
                        .WithMany("IngredientSubGroups")
                        .HasForeignKey("IngredientGroupId");

                    b.Navigation("IngredientGroup");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.RecipeIngredient", b =>
                {
                    b.HasOne("Quaverflow.Data.FoodModels.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredient")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quaverflow.Data.FoodModels.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.RecipeStep", b =>
                {
                    b.HasOne("Quaverflow.Data.FoodModels.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Mode", b =>
                {
                    b.HasOne("Quaverflow.Data.MusicModels.Scale", "Scale")
                        .WithMany("Modes")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Quaverflow.Data.CovidModels.Country", b =>
                {
                    b.Navigation("DailySummary");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredient");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientGroup", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("IngredientSubGroups");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.IngredientSubGroup", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Quaverflow.Data.FoodModels.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Quaverflow.Data.MusicModels.Scale", b =>
                {
                    b.Navigation("Modes");
                });
#pragma warning restore 612, 618
        }
    }
}
